### ISSUE TITLE
"Heat set" no longer stays set 

### ISSUE THREAD

**Issue by andrew-kennedy** [lukas-clarke/eight_sleep#11]
I noticed that despite the "heat set" endpoint seeming to work in that it doesn't error, the eight sleep app no longer stays heating for the duration you set. It always follows the "smart schedule", so any duration and temperature you set gets overridden in a few hours by the next "phase" of the smart schedule. I remember when I captured the app traffic most recently I noticed it's not too hard to set up the smart scheduling API. 

Would you be able to add functionality to set the 3 "smart schedule" temperatures? As right now you are forced to go back to the app and change all 3 temps even if you can set the "current" temp in home assistant.

**Comment by lukas-clarke** [comment]
Addressed in latest release.
