### ISSUE TITLE
Temperature sensor values question

### ISSUE THREAD

**Issue by billyjs** [lukas-clarke/eight_sleep#12]
Are the temperature sensors for room and each bed side accurate. The room temperature is pretty constant at 28C when the actual temp in the room in much lower (20-24ish varies though the day) and the bed temperatures are about consistent at 32C and 35C even when the cooling or heating is on.

**Comment by lukas-clarke** [comment]
From what I recall, there is an API call that can get various trend data from eight sleep, the the bed temperature sensor uses this. From my own use, the bed temp from this isn't very accurate. I could check the API calls that are now available to see if there is a more accurate way to pull data, but I personally haven't found a use for the bed temperature sensor.

**Comment by lukas-clarke** [comment]
This is addressed in the latest release (1.0.9).
