### ISSUE TITLE
Enhancement - Add current temp settings for each side

### ISSUE THREAD

**Issue by rsteckler** [lukas-clarke/eight_sleep#14]
Love that you re-created this and got it working again.

Can you add the current temp setting for each side?

**Comment by lukas-clarke** [comment]
To clarify, you want to see the bed cover temperatures as sensors? 
There are temperature sensors already, that were inherited from the previous integration. Are those not reliable/accurate for you?
What unit would you like to see the temperature in? What unit are you seeing the current bed temperature sensors in?

**Comment by rsteckler** [comment]
I'd like to see the *target* setting.  This is switchable in the Eight app to either an arbitrary -10 to +10, or as a target temperature.

Right now, the service calls to increment or set a target are write-only.  There's no way to see what the current setting is.

Here's a screen from the app:

![image](https://github.com/lukas-clarke/eight_sleep/assets/1714230/a462bf7b-6c80-44f6-b4ed-f1ff263823c5)

I believe the "-3" represents the current temperature that you currently expose.  I'm looking for the target of "10" as a new sensor.

**Comment by lukas-clarke** [comment]
Oh, understood. I would like to update the integration to be able to natively edit the device instead of using service calls. But this would require a larger re-write and I'm pretty busy for the near future

**Comment by rsteckler** [comment]
First, I totally get it.  Working on an open source project while also having a "real" job, family, hobbies etc is tough.  Been there.

Second, nevermind.  I just realized the setting is an attribute of the bed state.  I was just expecting it to be an entity.  My bad!

Closing :)
