### ISSUE TITLE
Enhancement request: change bed user

### ISSUE THREAD

**Issue by alvarezb** [lukas-clarke/eight_sleep#20]
The eight sleep app supports more than 2 users, and has tools to switch between them. It would be awesome to expose those hooks, allowing geolocation or presence based automated bed user switching

**Comment by lukas-clarke** [comment]
Could you elaborate on this? I'm not sure what this functionality looks like. Could you describe how to emulate it in the app, and use cases?

**Comment by lukas-clarke** [comment]
Closing issue
