### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by Isotope1** [lukas-clarke/eight_sleep#3]
After adding as a custom integration in HACS, restarting, then attempting to add as an integration with only a username and password, I receive an immediate error of "Unknown error occurred."

**Comment by ampersandru** [comment]
same issue here

**Comment by lukas-clarke** [comment]
@Isotope1 @ampersandru , it looks like I messed up the files when I was merging them from my dev environment. Just issued a hotfix (release 1.0.4) that should fix the issue you're seeing.

**Comment by lukas-clarke** [comment]
Closing this issue, as it has been fixed
