### ISSUE TITLE
Sleep stages

### ISSUE THREAD

**Issue by fstolze** [lukas-clarke/eight_sleep#30]
Sleep stages are documented in the project as unreliable and indeed sleep stage changes are missed.  Is there any strategy with which this data could be improved?

**Comment by lukas-clarke** [comment]
Unfortunately, not really. Unless 8 sleep decides to expose that info in the app.

**Comment by fstolze** [comment]
The info is in the app. But what's shown in the app seems to be different from what the sensor reports.

**Comment by lukas-clarke** [comment]
You see live sleep stages in the app? Would you mind including a screenshot, I can't find where this info is.

**Comment by fstolze** [comment]
![Screenshot_20240528_122849_Eight Sleep](https://github.com/lukas-clarke/eight_sleep/assets/40147910/92a0bd11-05e1-4e39-976f-ed8cbbea6f10)

Is this what you mean?

**Comment by lukas-clarke** [comment]
That looks like the info that the app provides after a sleep session is concluded. Does your app provide accurate sleep stages as they are occurring?

**Comment by fstolze** [comment]
You are correct. The sleep stages seem to get recalculated after the sleep session has concluded. H.A. collects and stores the data in real-time, which is why they are likely different.

**Comment by oliviertassinari** [comment]
I have done some research on this; the data I have for the same day:

- Eight Sleep app. Baseline

<img width="349" height="547" alt="Image" src="https://github.com/user-attachments/assets/77650d9b-99b9-407f-bbc1-0734b9a87706" />

- Eight Sleep Home Assistant (here). Completely off
<img width="852" height="170" alt="Image" src="https://github.com/user-attachments/assets/61bf08f4-83fd-475d-9eea-1cab4366624c" />

- Eight Sleep -> Google Health. More or less correct
<img width="349" alt="Image" src="https://github.com/user-attachments/assets/674216ee-9eb3-49ba-8cc5-831951989a98" />

The aggregated data can be pulled in Home Assistant with https://github.com/ResiyHome/resiyhome-health-sync. 

<img width="170" height="190" alt="Image" src="https://github.com/user-attachments/assets/1ef51893-70eb-4f21-ae7b-317ef61df699" />
