### ISSUE TITLE
Log Details (WARNING)

### ISSUE THREAD

**Issue by neildsb** [lukas-clarke/eight_sleep#32]
Hi, its just a warning -

Core
2024.6.0
Supervisor
2024.06.0
Operating System
12.3
Frontend
20240605.0

Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 8:11:58 am (597 occurrences)
Last logged: 8:12:01 am

Detected blocking call to open inside the event loop by custom integration 'eight_sleep' at custom_components/eight_sleep/pyEight/eight.py, line 179: timezone = pytz.timezone(self.timezone) (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/lukas-clarke/eight_sleep/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/eight_sleep/__init__.py", line 138, in async_setup_entry await user_coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() File "/config/custom_components/eight_sleep/pyEight/eight.py", line 233, in update_user_data await obj.update_user() File "/config/custom_components/eight_sleep/pyEight/user.py", line 670, in update_user await self.update_routines_data() File "/config/custom_components/eight_sleep/pyEight/user.py", line 846, in update_routines_data self.next_alarm = self.device.convert_string_to_datetime(nextTimestamp) File "/config/custom_components/eight_sleep/pyEight/eight.py", line 179, in convert_string_to_datetime timezone = pytz.timezone(self.timezone)

**Comment by ThioJoe** [comment]
Yea seeing the same thing
