### ISSUE TITLE
Setting away mode makes bed temperature entity unavailable 

### ISSUE THREAD

**Issue by akaplan07** [lukas-clarke/eight_sleep#34]
If I use the service to set the away mode on my partner's bed side, their bed temperature entity becomes unavailable. That means I haven't been able to clear the away mode, since the call to the set bed side service will fail without a valid bed temperature entity.

**Comment by lukas-clarke** [comment]
I'll try to take a look at this later in the week/next weekend.

**Comment by lukas-clarke** [comment]
@akaplan07, would you mind either pushing to a branch or creating a PR, and I'll try and get your fix merged in this weekend.
