### ISSUE TITLE
Ability to set alarm via service?

### ISSUE THREAD

**Issue by RIP21** [lukas-clarke/eight_sleep#35]
Hey, amazing integration. Thank you a lot for that!

Is there a way to set an alarm via this integration? I don't seem to see such a service. So I guess not, but wondering if there is a way to do it.

I'm asking because I like to use Next Alarm in my Android (Pixel) device as a source of truth and then basically sync all other alarms that some devices may have. 
So when I set the alarm, I automatically have an automation that will open curtains 10 minutes before the alarm. In this case, I want to sync Alarm in my Pixel with Sleep Eight without me moving a muscle :)

**Comment by lukas-clarke** [comment]
Hey @RIP21, see the conversation at https://github.com/lukas-clarke/eight_sleep/issues/19 for more details on this. Personally I set my alarms in HA vi a time variable on my dashboard and have that control all my other alarms.
