### ISSUE TITLE
Request: Ability to read side assignments

### ISSUE THREAD

**Issue by jordancoleman** [lukas-clarke/eight_sleep#41]
When my partner is away, I like to sleep across the whole bed, so I reassign my bed "side" to "both". When she returns, I assign her to one side and myself to the other. This works great with a Home Assistant automation calling "Set Bed Side", but there doesn't seem to be a way read back the side assignments to display in a dashboard. Could it be possible to access the side assignment for each user as a sensor?

**Comment by lukas-clarke** [comment]
Yes, I believe this data is in the API. I will try to take a look later this week

**Comment by lukas-clarke** [comment]
@jordancoleman, heads up that I have this working in a local branch and am hoping to cut a release in the next couple days
