### ISSUE TITLE
Alarm Idea for Adaptive Lighting

### ISSUE THREAD

**Issue by thk-socal** [lukas-clarke/eight_sleep#5]
If you could use the API to return the current time for the alarm on each side of bed, that would be amazing to drive adaptive lighting so that at the same time the bed starts warming up, the adaptive lighting can start turning on. Would really feel more like a sunrise and the heat of the sun warming you awake. Would also mean that the lights would auto adjust to the changes in the alarm set on the bed.

**Comment by lukas-clarke** [comment]
I can't remember exactly of the to of my head, but I think the API let's you query for next alarm. I'll try and take a look this upcoming weekend

**Comment by lukas-clarke** [comment]
@thk-socal implemented in latest release

**Comment by iGageit** [comment]
Is there a way to Set an alarm in HA?
