### ISSUE TITLE
Unable to add to Home Assistant 2024.10.1

### ISSUE THREAD

**Issue by Sinaloit** [lukas-clarke/eight_sleep#57]
When I attempt to add this custom repository it informs me that it is not a valid repository.  Per the documentation there needs to be a respository.yaml file at the root level, I suspect that is the cause:
https://developers.home-assistant.io/docs/add-ons/repository/

**Comment by Sinaloit** [comment]
Apparently, I misunderstood and this is designed to be added to another addon within Home Assistant.  Is it possible to add directly or only through adding HACS first?

**Comment by lukas-clarke** [comment]
This isn’t designed as an addon. You should be able to add as a custom
integration through HACS, you just need to add the URL as a custom
repository first.

**Comment by Sinaloit** [comment]
I installed HACS and was able to get it installed thanks.
