### ISSUE TITLE
Blocking call detected by HA

### ISSUE THREAD

**Issue by kapstaad** [lukas-clarke/eight_sleep#67]
This appeared in the system log after updating HA Core to 2004.10.4.  It could have been happening before, but I was checking the logs today after the Core update, and its the first time I've seen the error:

"2024-10-26 10:35:24.806 WARNING (MainThread) [homeassistant.util.loop] **Detected blocking call to open** with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'eight_sleep' at custom_components/eight_sleep/pyEight/eight.py, line 193: timezone = pytz.timezone(self.timezone) (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/lukas-clarke/eight_sleep/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open"

FWIW I live in Georgia, USA (not Abidjan, Africa?!) and my HA is set to the Eastern time zone.

**Comment by lukas-clarke** [comment]
This is fixed in the latest release
