### ISSUE TITLE
Only See Sensors and Note Devices

### ISSUE THREAD

**Issue by JDogg016** [lukas-clarke/eight_sleep#7]
Good Morning,

When I install and connect the new EIGHT Sleep Add-On, I only see sensors.  I do not see a climate entity (for temperature), nor do I see switches.

Am I doing something wrong? 

Also, if I try to install Eight Sleep Climate by adding the integration, I receive this message:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

I do not know whether this is related?

**Comment by DJPWeb** [comment]
Same here. As a note I don't have "sides" configured in the app, only a global temperature control.

Eight Sleep Integration update
update.eight_sleep_integration_update
HACS
—

Eight Sleep Room Temperature
sensor.eight_sleep_room_temperature
Eight Sleep
Room
—

XXX's Bed Presence
binary_sensor.xxx_s_bed_presence
Eight Sleep
Room
—

XXX's Bed State
sensor.xxx_s_bed_state
Eight Sleep
Room
—

XXX's Bed Temperature
sensor.xxx_s_bed_temperature
Eight Sleep
Room
—

XXX's Next Alarm
sensor.xxx_s_next_alarm
Eight Sleep
Room
—

XXX's Previous Sleep Session
sensor.xxx_s_previous_sleep_session
Eight Sleep
Room
—

XXX's Sleep Fitness
sensor.xxx_s_sleep_fitness
Eight Sleep
Room
—

XXX's Sleep Session
sensor.xxx_s_sleep_session
Eight Sleep
Room
—

XXX's Sleep Stage
sensor.xxx_s_sleep_stage
Eight Sleep
Room

**Comment by lukas-clarke** [comment]
@DJPWeb are you seeing the "Config flow..." error message as well?
Are you able to use the Eight Sleep services outlined in the readme to control the temperature entity?

**Comment by JDogg016** [comment]
I see the config flow error and, no, I cannot use the call services (ie. climate) because they are not visible

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lukas-clarke** [comment]
Ok, thanks for the info. I'll try to take a look soon

**Comment by lukas-clarke** [comment]
I'm having a hard time recreating this error. I removed my partner from the bed and re-setup the integration with just my account on the bed. 
I'm getting the devices for both the bed account, and my user account.
![image](https://github.com/lukas-clarke/eight_sleep/assets/88019203/bc476db5-3724-4062-b4e6-c807602790a2)

Most importantly, I'm getting my user account's bed temperature sensor:
sensor.<XXX>_s_bed_temperature.

I'm also seeing the services available, and tested them as working.


![image](https://github.com/lukas-clarke/eight_sleep/assets/88019203/3c0fcfbd-0a5b-45d9-afdd-a1ed7d21c135)

![image](https://github.com/lukas-clarke/eight_sleep/assets/88019203/5cb95a55-f87c-4dc8-b907-2bbc0acebf35)

**Comment by DJPWeb** [comment]
OK, thanks, with the example I understood my mistake, I was actually looking for an Entity instead of a Service (I admit I'm new to HA). Now I understand the flow / process to properly use the services. Sorry about that.

**Comment by lukas-clarke** [comment]
@DJPWeb, no worries, glad you were able to get it working. I'll add some screenshots to the Readme for the next release to clarify how the services work.

@JDogg016, are you still seeing the issue?

**Comment by lukas-clarke** [comment]
Added more documentation to latest release
