### ISSUE TITLE
add GET for /v1/users/{self.user_id}/temperature to pyEight

### ISSUE THREAD

**Issue by keatontaylor** [lukas-clarke/eight_sleep#9]
When calling `/v1/users/{self.user_id}/temperature` via a GET call it returns the current smart state of the mattress.

```
{
  "currentLevel": 0,
  "currentDeviceLevel": -51,
  "currentState": {
    "type": "off",
    "instance": {
      "timestamp": "2023-11-27T13:37:55Z"
    }
  },
  "scheduleType": "smart",
  "smart": {
    "bedTimeLevel": 0,
    "initialSleepLevel": 0,
    "finalSleepLevel": 0
  },
  "timeBased": {
    "level": -10,
    "durationSeconds": 28800
  }
}
```

['currentState']['type'] represents the state of the mattress as seen in the 8-sleep app for the schedule. With the following options:

off = when the mattress side is completely off
smart:bedtime = when the mattress is precooling or preheating for the selected bedtime (begins one hour before bedtime)
smart:initial = when the mattress has detected the person on this bedside has fallen asleep (lasts for 4 hrs)
smart:final = after the 4 hr window the mattress goes into the temperature set in the "final" stage in the app (stays in this stage until alarm or off)
alarm = 1 hr prior to the alarm time the app to begin heating and cooling the bed to the alarm temp.

Integrating this into the attributes for the mattress side state would allow automations to key off of the 4 phases that can be set in the 8-sleep app. Such as setting the lights to a lower brightness when the smart:bedtime state is detected, or opening the blinds after 30 mins when the alarm state is detected.

**Comment by keatontaylor** [comment]
Not sure what you mean by your question currentState should ask be away? 

However, for the second question as far as I can tell the bed presence is not reported directly in the API and I do not see any values that would help determine if the bed actually has someone in it besides getting sleep data (light, rem, deep) from the trends.

**Comment by lukas-clarke** [comment]
Edited my comment for clarity: * "also be away"

**Comment by keatontaylor** [comment]
Ah not 100% sure, I think when you put the mattress side into away mode if say you're on vacation it does not return any values for the user ID calls.

**Comment by lukas-clarke** [comment]
Addressed in latest release.
